// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddContent() {
  return window['go']['main']['App']['AddContent']();
}

export function AddUserWithEmail(arg1, arg2) {
  return window['go']['main']['App']['AddUserWithEmail'](arg1, arg2);
}

export function ArrayDebug(arg1) {
  return window['go']['main']['App']['ArrayDebug'](arg1);
}

export function CheckAuthStatus() {
  return window['go']['main']['App']['CheckAuthStatus']();
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function Debug(arg1) {
  return window['go']['main']['App']['Debug'](arg1);
}

export function DisplayFiles(arg1, arg2) {
  return window['go']['main']['App']['DisplayFiles'](arg1, arg2);
}

export function DisplaySharedUsers(arg1) {
  return window['go']['main']['App']['DisplaySharedUsers'](arg1);
}

export function DisplaySharedWorkspaceFiles(arg1, arg2) {
  return window['go']['main']['App']['DisplaySharedWorkspaceFiles'](arg1, arg2);
}

export function DownloadSharedWorkspace(arg1, arg2) {
  return window['go']['main']['App']['DownloadSharedWorkspace'](arg1, arg2);
}

export function ErrorMsg(arg1) {
  return window['go']['main']['App']['ErrorMsg'](arg1);
}

export function GetRemoteWorkspaces() {
  return window['go']['main']['App']['GetRemoteWorkspaces']();
}

export function GetRemoteWorkspacesV2() {
  return window['go']['main']['App']['GetRemoteWorkspacesV2']();
}

export function GetSharedWorkspaces() {
  return window['go']['main']['App']['GetSharedWorkspaces']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListAllFiles() {
  return window['go']['main']['App']['ListAllFiles']();
}

export function ListSpecificFiles(arg1) {
  return window['go']['main']['App']['ListSpecificFiles'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Nice(arg1) {
  return window['go']['main']['App']['Nice'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function Register(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3, arg4, arg5);
}

export function SetPermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPermission'](arg1, arg2, arg3);
}

export function SetUserPermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetUserPermission'](arg1, arg2, arg3);
}
