// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddContent():Promise<Array<any>>;

export function AddUserWithEmail(arg1:string,arg2:string):Promise<string>;

export function CheckAuthStatus():Promise<string>;

export function CreateWorkspace(arg1:string):Promise<string>;

export function Debug():Promise<void>;

export function DisplayFiles(arg1:string,arg2:string):Promise<Array<any>>;

export function DisplaySharedWorkspaceFiles(arg1:string,arg2:string):Promise<Array<any>>;

export function DownloadSharedWorkspace(arg1:string,arg2:string):Promise<void>;

export function ErrorMsg(arg1:string):Promise<void>;

export function GetRemoteWorkspaces():Promise<Array<string>>;

export function GetSharedWorkspaces():Promise<Array<any>>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function Nice(arg1:string):Promise<string>;

export function OpenFile(arg1:string):Promise<string>;
