// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddContent() {
  return window['go']['main']['App']['AddContent']();
}

export function AddUserWithEmail(arg1, arg2) {
  return window['go']['main']['App']['AddUserWithEmail'](arg1, arg2);
}

export function CheckAuthStatus() {
  return window['go']['main']['App']['CheckAuthStatus']();
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function DisplayFiles(arg1, arg2) {
  return window['go']['main']['App']['DisplayFiles'](arg1, arg2);
}

export function GetRemoteWorkspaces() {
  return window['go']['main']['App']['GetRemoteWorkspaces']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Nice(arg1) {
  return window['go']['main']['App']['Nice'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}
